title: Time Travelling Visualizer
description: A visualizer for deep learning training dynamics!
theme: just-the-docs

url: https://weiyu-kong.github.io/visualizer-docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
